name: Generate Docs
on:
  push:
    branches:
      - main
jobs:
  Typedocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore lerna cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        run: yarn
      - name: Build docs
        run: yarn docs
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: packages/core/docs
          target-folder: typedoc
          clean: true
      - name: Add .nojekyll
        run: |
          mkdir extra
          touch extra/.nojekyll
      - name: Deploy .nojekyll
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: extra
          clean: false
